"""Known-answer test corpus for trailmark parsers, diagram, and CLI.

Each fixture is a source file paired with a `.expected.json` snapshot of the
canonical CodeGraph output. Snapshots can be regenerated by setting
``TRAILMARK_UPDATE_SNAPSHOTS=1`` when running pytest; review the resulting
diff before committing.
"""
