"""Shared infrastructure for known-answer-test (KAT) snapshot tests.

A KAT entry is a pair `(fixture_file, expected_json)` under tests/fixtures/kat/.
Parsing the fixture should produce a CodeGraph whose normalized JSON form
matches the snapshot exactly. Snapshots are regenerated by setting the
environment variable ``TRAILMARK_UPDATE_SNAPSHOTS=1`` while running pytest.
"""

from __future__ import annotations

import json
import os
from pathlib import Path
from typing import Any

from trailmark.parse import parse_file
from trailmark.query.api import QueryEngine

FIXTURE_ROOT = Path(__file__).parent / "fixtures" / "kat"
UPDATE_ENV = "TRAILMARK_UPDATE_SNAPSHOTS"


def _normalize_paths(data: dict[str, Any], fixture_name: str) -> dict[str, Any]:
    """Replace absolute paths with the fixture basename so snapshots are stable.

    Walks the graph recursively: top-level ``root_path`` plus every ``file_path``
    key on any nested object (node location, branch location, etc.). Anything
    else that happens to be an absolute path inside the graph (e.g. dependency
    entries) is left alone.
    """
    data["root_path"] = fixture_name
    _rewrite_file_paths(data, fixture_name)
    return data


def _rewrite_file_paths(obj: Any, fixture_name: str) -> None:
    if isinstance(obj, dict):
        for key, value in obj.items():
            if key == "file_path" and isinstance(value, str):
                obj[key] = fixture_name
            else:
                _rewrite_file_paths(value, fixture_name)
    elif isinstance(obj, list):
        for item in obj:
            _rewrite_file_paths(item, fixture_name)


def parse_to_canonical(fixture: Path, language: str | None = None) -> dict[str, Any]:
    """Parse ``fixture`` and return a normalized canonical JSON dict.

    The returned dict round-trips through ``json.dumps(..., sort_keys=True)``
    so two runs on the same input always produce byte-identical output.
    """
    graph = parse_file(str(fixture), language=language)
    engine = QueryEngine.from_graph(graph)
    raw = json.loads(engine.to_json())
    return _normalize_paths(raw, fixture.name)


def assert_snapshot_matches(fixture: Path, snapshot: Path, language: str | None = None) -> None:
    """Compare the canonical parse output of ``fixture`` against ``snapshot``.

    If ``TRAILMARK_UPDATE_SNAPSHOTS=1``, write the actual output to the
    snapshot instead of asserting. Otherwise raise AssertionError on mismatch.
    """
    actual = parse_to_canonical(fixture, language=language)
    actual_text = json.dumps(actual, indent=2, sort_keys=True) + "\n"

    if os.environ.get(UPDATE_ENV) == "1":
        snapshot.write_text(actual_text)
        return

    if not snapshot.exists():
        msg = (
            f"Missing snapshot: {snapshot}\n"
            f"Run with {UPDATE_ENV}=1 to create it, then review the diff."
        )
        raise AssertionError(msg)

    expected_text = snapshot.read_text()
    if actual_text != expected_text:
        msg = (
            f"Snapshot mismatch for {fixture.name}.\n"
            f"Run with {UPDATE_ENV}=1 to regenerate {snapshot.name}, "
            f"then review the diff before committing."
        )
        raise AssertionError(msg)


def fixture_pair(language: str, basename: str) -> tuple[Path, Path]:
    """Return (fixture_path, snapshot_path) for the given language/basename."""
    lang_dir = FIXTURE_ROOT / language
    matches = list(lang_dir.glob(f"{basename}.*"))
    sources = [m for m in matches if not m.name.endswith(".expected.json")]
    if not sources:
        msg = f"No fixture source under {lang_dir} matching {basename}.*"
        raise FileNotFoundError(msg)
    if len(sources) > 1:
        msg = f"Ambiguous fixture sources under {lang_dir} for {basename}: {sources}"
        raise FileNotFoundError(msg)
    snapshot = lang_dir / f"{basename}.expected.json"
    return sources[0], snapshot
